<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibraryManagementSystem.Database\LibraryManagementSystem.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Book\" />
    <Folder Include="Models\Borrower\" />
    <Folder Include="Models\Borrowing\" />
  </ItemGroup>

</Project>
